const test = require('node:test');
const assert = require('node:assert/strict');
const { normalizePlanReview, validatePlanReview, applyConflictDecision, editUnit, confirmPlanReview, acceptPlanReview } = require('../app/lib/content-factory/course-planning/plan-review-model');

function fixture() { return normalizePlanReview({ planningVersion: 1, days: [{ dayNumber: 1, units: [{ id: 'u1', dayNumber: 1, unitNumber: 1, globalUnitNumber: 1, topic: 'Alt', content: 'Inhalt', competencyGoal: 'Ziel', workFormat: { key: 'individual', label: 'Einzelarbeit' } }] }], conflicts: [{ conflictId: 'c1', type: 'source_conflict', relevance: 'review_required', severity: 'warning', title: 'Abweichender Begriff', description: 'Quellen widersprechen sich.', affectedUnitIds: ['u1'], affectedFields: ['topic'], proposedValue: 'Neu' }, { conflictId: 'noise', title: 'OCR 00000 n', description: 'Extraktionsartefakt' }] }); }

test('Konflikte werden klassifiziert, verknüpft und Extraktionsrauschen blockiert nicht', () => { const plan = fixture(); assert.equal(plan.conflicts[1].type, 'extraction_issue'); assert.equal(plan.conflicts[1].relevance, 'ignored_as_extraction_noise'); assert.equal(validatePlanReview(plan).open.length, 1); });
test('KI-Vorschlag ändert das betroffene Feld und protokolliert die Entscheidung', () => { const plan = applyConflictDecision(fixture(), { conflictId: 'c1', resolutionStatus: 'accepted_ai_proposal' }); assert.equal(plan.days[0].units[0].topic, 'Neu'); assert.equal(plan.conflicts[0].resolutionStatus, 'accepted_ai_proposal'); assert.equal(plan.changeHistory[0].previousValue, 'Alt'); });
test('manuelle Änderung ist versioniert, öffnet Konflikte erneut und setzt Bestätigung zurück', () => { const plan = fixture(); plan.reviewState.confirmed = true; editUnit(plan, { unitId: 'u1', fieldName: 'content', newValue: 'Mehrzeilig\nmit Umlaut: Ä', changeOrigin: 'manual_edit' }); assert.equal(plan.changeHistory[0].newValue, 'Mehrzeilig\nmit Umlaut: Ä'); assert.equal(plan.reviewState.confirmed, false); });
test('Bestätigung und Annahme bleiben getrennt und werden strikt gegated', () => { const open = fixture(); assert.throws(() => confirmPlanReview(open), (error) => error.code === 'PLAN_REVIEW_BLOCKED'); const resolved = applyConflictDecision(open, { conflictId: 'c1', resolutionStatus: 'kept_original' }); confirmPlanReview(resolved); assert.equal(resolved.reviewState.confirmed, true); acceptPlanReview(resolved); assert.equal(resolved.reviewState.acceptedPlanningVersion, 1); });
test('ungültige UE- und Feldreferenzen werden abgelehnt', () => { const plan = fixture(); plan.conflicts[0].affectedUnitIds = ['unbekannt']; plan.conflicts[0].affectedFields = ['debugHtml']; const review = validatePlanReview(plan); assert.match(review.errors.join(' '), /unbekannte UE.*unbekanntes Feld/); });
