const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const path = require('path');
const progress = require('../app/renderer/tool-center/workflow-ui/workflow-progress');

test('Analyse und Planung verwenden dieselbe konfigurierbare Fortschrittskomponente', () => { const analysis = progress.render({ status: 'running', kind: 'analysis', message: 'Inhalte werden analysiert', totalItems: 5, currentItem: 2, overallProgress: .4, currentDocument: 'Sehr langer Dokumentname.pdf', history: [{ phase: 'document_preparation' }, { phase: 'document_analysis' }], phase: 'document_analysis' }); const planning = progress.render({ status: 'running', kind: 'planning', message: 'Themen werden verteilt' }); assert.match(analysis, /Dokumentanalyse.*Wird verarbeitet/); assert.match(analysis, /40% · 2 von 5/); assert.match(analysis, /Sehr langer Dokumentname/); assert.match(planning, /Unterrichtsplanerstellung.*Wird verarbeitet/); assert.match(planning, /workflow-progress-indeterminate/); });
test('Warteschlange, Fehler, Abbruch und deutsche Statuswerte sind verständlich', () => { assert.match(progress.render({ status: 'queued' }), /In der Warteschlange/); assert.match(progress.render({ status: 'failed', errors: ['Sichere Fehlermeldung'] }), /Erneut versuchen/); assert.match(progress.render({ status: 'cancelled' }), /Abgebrochen/); assert.match(progress.render({ status: 'timed_out' }), /Zeitüberschreitung/); });
test('Terminale Statuswerte lassen keine blaue laufende Kachel zurück', () => { for (const state of ['completed', 'completed_with_warnings', 'failed', 'cancelled']) { const html = progress.render({ status: state, phase: 'plan_validation', history: [{ phase: 'planning_input' }, { phase: 'plan_validation' }], overallProgress: state.startsWith('completed') ? 1 : .8 }); assert.doesNotMatch(html, /step-running/); } assert.match(progress.render({ status: 'running', phase: 'plan_validation', history: [{ phase: 'plan_validation' }] }), /step-running/); });
test('Renderer bindet nur die gemeinsame Fortschrittskomponente ein', () => { const root = path.join(__dirname, '..', 'app', 'renderer', 'tool-center'); const ui = fs.readFileSync(path.join(root, 'factory.js'), 'utf8'); const html = fs.readFileSync(path.join(root, 'factory.html'), 'utf8'); assert.match(ui, /workflowProgress\.render\(wizard\.analysisProgress\)/); assert.doesNotMatch(ui, /class="analysis-progress"/); assert.match(html, /workflow-ui\/workflow-progress\.js/); });
